<?php

namespace Database\Seeders;

use App\Models\Skill;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class SkillSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Skill::insert([
            [
                'name'       => 'HTML',
                'icon'       => 'html-icon.svg',
                'description'=> 'Markup language for creating web pages',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'CSS',
                'icon'       => 'css-icon.svg',
                'description'=> 'Style sheet language for designing web layouts',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'SCSS',
                'icon'       => 'scss-icon.svg',
                'description'=> 'CSS preprocessor supporting variables and nesting',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'JavaScript',
                'icon'       => 'js-icon.svg',
                'description'=> 'Scripting language for interactive web features',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Jquery',
                'icon'       => 'jquery-icon.svg',
                'description'=> 'JavaScript library for simplified DOM traversal and events',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Alpine',
                'icon'       => 'alpine-icon.svg',
                'description'=> 'Lightweight JavaScript framework for declarative UI behavior',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'PHP',
                'icon'       => 'php-icon.svg',
                'description'=> 'Server-side scripting language for web development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Python',
                'icon'       => 'python-icon.svg',
                'description'=> 'General-purpose language with extensive ecosystem',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'C#',
                'icon'       => 'csharp-icon.svg',
                'description'=> 'Object-oriented language for .NET development',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Java',
                'icon'       => 'java-icon.svg',
                'description'=> 'Object-oriented language for cross-platform applications',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Bootstrap',
                'icon'       => 'bootstrap-icon.svg',
                'description'=> 'CSS framework for responsive design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'CircuitPython',
                'icon'       => 'circuitpython-icon.svg',
                'description'=> 'Python variant optimized for microcontrollers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Laravel',
                'icon'       => 'laravel-icon.svg',
                'description'=> 'PHP framework for elegant web applications',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Tailwind CSS',
                'icon'       => 'tailwind-icon.svg',
                'description'=> 'Utility-first CSS framework for UI design',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Pandas',
                'icon'       => 'pandas-icon.svg',
                'description'=> 'Python library for data analysis and manipulation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Matplotlib',
                'icon'       => 'matplotlib-icon.svg',
                'description'=> 'Plotting library for creating static, animated graphs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Scikit-learn',
                'icon'       => 'sklearn-icon.svg',
                'description'=> 'Python library for machine learning algorithms',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'SpringBoot',
                'icon'       => 'springboot-icon.svg',
                'description'=> 'Java framework for building microservices',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'REST',
                'icon'       => 'rest-icon.svg',
                'description'=> 'Architectural style for web APIs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Qlik',
                'icon'       => 'qlik-icon.svg',
                'description'=> 'Business Intelligence and data visualization platform',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'OrangePi',
                'icon'       => 'orangepi-icon.svg',
                'description'=> 'Single-board computer for embedded projects',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Networking',
                'icon'       => 'networking-icon.svg',
                'description'=> 'Principles of computer networks and protocols',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // DevOps & Tools
            [
                'name'       => 'Git',
                'icon'       => 'git-icon.svg',
                'description'=> 'Distributed version control system',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Docker',
                'icon'       => 'docker-icon.svg',
                'description'=> 'Platform for containerizing applications',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Docker Compose',
                'icon'       => 'compose-icon.svg',
                'description'=> 'Tool for defining multi-container Docker environments',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'FreeCAD',
                'icon'       => 'freecad-icon.svg',
                'description'=> 'Open-source 3D CAD modeling software',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'IoT electronics',
                'icon'       => 'iot-icon.svg',
                'description'=> 'Hardware components for Internet of Things projects',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'CyberSecurity concepts',
                'icon'       => 'csconcepts-icon.svg',
                'description'=> 'Fundamental concepts in cybersecurity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'CyberSecurity Laws',
                'icon'       => 'cslaws-icon.svg',
                'description'=> 'Legal regulations and standards for cybersecurity',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Photoshop',
                'icon'       => 'photoshop-icon.svg',
                'description'=> 'Raster graphics editing software',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Prototyping',
                'icon'       => 'prototyping-icon.svg',
                'description'=> 'Process of creating early product models',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Requirements Analysis',
                'icon'       => 'requireanalys-icon.svg',
                'description'=> 'Technique for gathering and documenting system needs',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Value Proposition',
                'icon'       => 'valuep-icon.svg',
                'description'=> 'Framework for defining product benefits to customers',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => "7's model",
                'icon'       => '7smodel-icon.svg',
                'description'=> 'McKinsey 7S framework for organizational analysis',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'React',
                'icon'       => 'react-icon.svg',
                'description'=> 'JavaScript library for building user interfaces',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Machine learning',
                'icon'       => 'ml-icon.svg',
                'description'=> 'Algorithms that enable systems to learn from data',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Deep learning',
                'icon'       => 'dl-icon.svg',
                'description'=> 'Neural network-based learning techniques',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'BPMN Modeling',
                'icon'       => 'bpmn-icon.svg',
                'description'=> 'Business Process Model and Notation for workflows',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Livewire',
                'icon'       => 'livewire-icon.svg',
                'description'=> 'Laravel library for reactive components',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'SQL',
                'icon'       => 'sql-icon.svg',
                'description'=> 'Query language for databases',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'MongoDB',
                'icon'       => 'mongo.svg',
                'description'=> 'Query language for databases',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'SQLite',
                'icon'       => 'sql-icon.svg',
                'description'=> 'Query language for databases',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Linux',
                'icon'       => 'linux-icon.svg',
                'description'=> 'Open-source OS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Window server',
                'icon'       => 'windows-icon.svg',
                'description' => 'Operating system by Microsoft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Scripting',
                'icon'       => 'scripting-icon.svg',
                'description' => 'Operating system by Microsoft',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'UML',
                'icon'       => 'uml-icon.svg',
                'description'=> 'Modeling notation',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Formal Communication',
                'icon'       => 'formal-communication-icon.svg',
                'description'=> 'Communicating clearly and professionally in formal contexts.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Personal Branding',
                'icon'       => 'personal-branding-icon.svg',
                'description'=> 'Building and maintaining a strong personal brand identity.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Pitching',
                'icon'       => 'pitching-icon.svg',
                'description'=> 'Delivering persuasive pitches to sell ideas or products.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Presenting',
                'icon'       => 'presenting-icon.svg',
                'description'=> 'Effectively presenting information to an audience.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Team Meetings',
                'icon'       => 'team-meetings-icon.svg',
                'description'=> 'Collaborating and communicating efficiently in meetings.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Team Conflict',
                'icon'       => 'team-conflict-icon.svg',
                'description'=> 'Managing and resolving conflicts within a team.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Scientific Writing',
                'icon'       => 'scientific-writing-icon.svg',
                'description'=> 'Writing research papers and technical documents clearly and formally.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Cultural Awareness',
                'icon'       => 'cultural-awareness-icon.svg',
                'description'=> 'Understanding and respecting cultural differences.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Intercultural Competencies',
                'icon'       => 'intercultural-competencies-icon.svg',
                'description'=> 'Working effectively across different cultures.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Hofstede Dimensions',
                'icon'       => 'hofstede-dimensions-icon.svg',
                'description'=> 'Applying Hofstede’s cultural dimensions theory in practice.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Negotiations',
                'icon'       => 'negotiations-icon.svg',
                'description'=> 'Reaching agreements through dialogue and compromise.',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
