import { MediaFile } from '../models/media-file.model';

const timestamp = '2025-10-01T09:00:00Z';

export const MEDIA_FILES: MediaFile[] = [
  {
    id: 'file-avatar-alex',
    bucketName: 'portfolio',
    objectKey: 'profiles/alex/avatar.png',
    originalFilename: 'alex-avatar.png',
    storedFilename: 'alex-avatar-1.png',
    mimeType: 'image/png',
    fileSizeBytes: 248130,
    checksum: 'sha256-avatar-alex',
    publicUrl: '/assets/mock/profile-avatar.png',
    altText: 'Portrait placeholder for Alex van Poppel',
    title: 'Profile avatar',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-hero-portrait',
    bucketName: 'portfolio',
    objectKey: 'profiles/alex/hero.png',
    originalFilename: 'hero.png',
    storedFilename: 'hero-1.png',
    mimeType: 'image/png',
    fileSizeBytes: 612004,
    checksum: 'sha256-hero-alex',
    publicUrl: '/assets/mock/hero-image.png',
    altText: 'Hero image placeholder for the portfolio',
    title: 'Hero image',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-resume',
    bucketName: 'portfolio',
    objectKey: 'profiles/alex/resume.pdf',
    originalFilename: 'alex-van-poppel-resume.pdf',
    storedFilename: 'resume-2025.pdf',
    mimeType: 'application/pdf',
    fileSizeBytes: 152320,
    checksum: 'sha256-resume-alex',
    publicUrl: '/assets/mock-resume.pdf',
    title: 'Resume',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-project-portfolio-cover',
    bucketName: 'portfolio',
    objectKey: 'projects/personal-portfolio/cover.png',
    originalFilename: 'personal-portfolio-cover.png',
    storedFilename: 'project-cover-portfolio.png',
    mimeType: 'image/png',
    fileSizeBytes: 480221,
    checksum: 'sha256-project-portfolio-cover',
    publicUrl: '/assets/mock/projects/personal-portfolio-cover.png',
    altText: 'Wireframe-inspired portfolio layout mock-up',
    title: 'Portfolio project cover image',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-project-plant-cover',
    bucketName: 'portfolio',
    objectKey: 'projects/plant-care-app/cover.png',
    originalFilename: 'plant-care-cover.png',
    storedFilename: 'project-cover-plant.png',
    mimeType: 'image/png',
    fileSizeBytes: 390110,
    checksum: 'sha256-project-plant-cover',
    publicUrl: '/assets/mock/projects/plant-care-cover.png',
    altText: 'Plant care dashboard concept',
    title: 'Plant care project cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-project-motogp-cover',
    bucketName: 'portfolio',
    objectKey: 'projects/motogp-ticketing/cover.png',
    originalFilename: 'motogp-cover.png',
    storedFilename: 'project-cover-motogp.png',
    mimeType: 'image/png',
    fileSizeBytes: 400235,
    checksum: 'sha256-project-motogp-cover',
    publicUrl: '/assets/mock/projects/motogp-cover.png',
    altText: 'MotoGP booking interface mock-up',
    title: 'MotoGP project cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-project-dino-cover',
    bucketName: 'portfolio',
    objectKey: 'projects/dino-classifier/cover.png',
    originalFilename: 'dino-cover.png',
    storedFilename: 'project-cover-dino.png',
    mimeType: 'image/png',
    fileSizeBytes: 360421,
    checksum: 'sha256-project-dino-cover',
    publicUrl: '/assets/mock/projects/dino-cover.png',
    altText: 'Dataset and model-training workflow diagram',
    title: 'Dinosaur classifier cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-project-auction-cover',
    bucketName: 'portfolio',
    objectKey: 'projects/auction-house-api/cover.png',
    originalFilename: 'auction-cover.png',
    storedFilename: 'project-cover-auction.png',
    mimeType: 'image/png',
    fileSizeBytes: 342111,
    checksum: 'sha256-project-auction-cover',
    publicUrl: '/assets/mock/projects/auction-cover.png',
    altText: 'Auction workflow and service architecture sketch',
    title: 'Auction API cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-blog-shell-cover',
    bucketName: 'portfolio',
    objectKey: 'blog/building-a-portfolio-shell/cover.png',
    originalFilename: 'portfolio-shell-cover.png',
    storedFilename: 'blog-shell-cover.png',
    mimeType: 'image/png',
    fileSizeBytes: 320811,
    checksum: 'sha256-blog-shell-cover',
    publicUrl: '/assets/mock/blog/portfolio-shell-cover.png',
    altText: 'Portfolio shell layout illustration',
    title: 'Portfolio shell article cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-blog-mock-data-cover',
    bucketName: 'portfolio',
    objectKey: 'blog/mock-data-first/cover.png',
    originalFilename: 'mock-data-cover.png',
    storedFilename: 'blog-mock-data-cover.png',
    mimeType: 'image/png',
    fileSizeBytes: 312213,
    checksum: 'sha256-blog-mock-data-cover',
    publicUrl: '/assets/mock/blog/mock-data-cover.png',
    altText: 'Mock data objects represented as cards',
    title: 'Mock data article cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-blog-storytelling-cover',
    bucketName: 'portfolio',
    objectKey: 'blog/student-projects-and-storytelling/cover.png',
    originalFilename: 'storytelling-cover.png',
    storedFilename: 'blog-storytelling-cover.png',
    mimeType: 'image/png',
    fileSizeBytes: 315773,
    checksum: 'sha256-blog-storytelling-cover',
    publicUrl: '/assets/mock/blog/storytelling-cover.png',
    altText: 'Cards representing project storytelling',
    title: 'Storytelling article cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  },
  {
    id: 'file-blog-components-cover',
    bucketName: 'portfolio',
    objectKey: 'blog/components-before-polish/cover.png',
    originalFilename: 'components-cover.png',
    storedFilename: 'blog-components-cover.png',
    mimeType: 'image/png',
    fileSizeBytes: 302921,
    checksum: 'sha256-blog-components-cover',
    publicUrl: '/assets/mock/blog/components-cover.png',
    altText: 'UI components arranged in a grid',
    title: 'Components article cover',
    visibility: 'public',
    uploadedBy: null,
    createdAt: timestamp,
    updatedAt: timestamp
  }
];
