from app.domains.admin.schema_parts.activity import *
from app.domains.admin.schema_parts.assistant import *
from app.domains.admin.schema_parts.auth import *
from app.domains.admin.schema_parts.common import *
from app.domains.admin.schema_parts.content import *
from app.domains.admin.schema_parts.media import *
from app.domains.admin.schema_parts.navigation import *
from app.domains.admin.schema_parts.overview import *
from app.domains.admin.schema_parts.profile import *
from app.domains.admin.schema_parts.stats import *
from app.domains.admin.schema_parts.taxonomy import *
